Filter by duration
bensle/capstone-project pull request #6
Opened 2022-06-29 10:32 UTC by bensle

2022-06-29 16:00 UTC, stefankorder requested changes
Take a look at my comments.

2022-06-29 16:00 UTC, stefankorder commented on src/components/ActivityCard/ActivityCard.js
> +      <ul role="list">
The element ul has an implicit role of list. Defining this explicitly is redundant and should be avoided.

2022-06-29 16:00 UTC, stefankorder commented on src/App.js
> +      <DurationFilter activities={activities} setActivities={setActivities} />
It's better not to lift down a state's set function. Instead you should lift down a special function witch call the set function.

2022-06-29 16:00 UTC, stefankorder commented on src/components/DurationFilterButton/DurationFilter.js
> +    // console.log(results);
You should delete unnecessary console log functions

2022-06-29 16:00 UTC, stefankorder commented on src/components/DurationFilterButton/DurationFilter.js
> +  const [selectedRadioButton, setSelectedRadioButton] = useState();
if you dont use a variable you should not define it.

2022-06-29 16:00 UTC, stefankorder commented on src/components/DurationFilterButton/DurationFilter.js
> +          onClick={() => filterDuration('short')}
You could use selectedRadioButton at this point, so the variable is not useless.

2022-06-29 16:00 UTC, stefankorder commented on src/components/DurationFilterButton/DurationFilter.js
> +          onClick={() => filterDuration('weekend')}
You could use selectedRadioButton at this point, so the variable is not useless.

2022-06-29 16:00 UTC, stefankorder commented on src/components/DurationFilterButton/DurationFilter.js
> +          onClick={() => filterDuration('vacation')}
You could use selectedRadioButton at this point, so the variable is not useless.

2022-06-29 16:00 UTC, stefankorder commented on src/components/DurationFilterButton/DurationFilter.js
> +          onChange={event => setSelectedRadioButton(event.target.value)}
In your case it is better to not use two events.

2022-06-29 16:00 UTC, stefankorder commented on src/components/DurationFilterButton/DurationFilter.js
> +          onChange={event => setSelectedRadioButton(event.target.value)}
In your case it is better to not use two events.

2022-06-29 16:00 UTC, stefankorder commented on src/components/DurationFilterButton/DurationFilter.js
> +          onChange={event => setSelectedRadioButton(event.target.value)}
In your case it is better to not use two events.

2022-06-29 16:00 UTC, stefankorder commented on src/components/DurationFilterButton/DurationFilter.js
> +          onChange={event => setSelectedRadioButton(event.target.value)}
In your case it is better to not use two events.

2022-06-29 19:11 UTC, bensle commented on src/components/ActivityCard/ActivityCard.js
> +      <ul role="list">
Since the list has style:none the role is set for accessibility reasons

2022-06-29 19:22 UTC, bensle commented on src/App.js
> +      <DurationFilter activities={activities} setActivities={setActivities} />
Regarding the other comments/suggestions: i deleted the radiobutton state and the onChange. Dont need any of them at the moment. I lifted up the filter function and passed everything needed down again (including the setState as special function.

2022-06-30 07:10 UTC, stefankorder commented on src/components/ActivityCard/ActivityCard.js
> +      <ul role="list">
A list does not need a role because it is already recognized as such.

2022-06-30 07:22 UTC, stefankorder commented on src/components/ActivityCard/ActivityCard.js
> +      <ul role="list">
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/list_role

2022-06-30 07:32 UTC, bensle commented on src/components/ActivityCard/ActivityCard.js
> +      <ul role="list">
https://www.tempertemper.net/blog/accessibility-issues-when-removing-list-markers

thats what we learned in class. If a list gets list-style-none -> role:list has to be set for screenreaders.

2022-06-30 07:36 UTC, stefankorder commented on src/components/ActivityCard/ActivityCard.js
> +      <ul role="list">
Okay with list-style-**type** you are right, i thought you just remove the style and not the **type**

2022-06-30 07:36 UTC, stefankorder approved these changes
👍🏻

2022-06-30 08:28 UTC, merged